#!/bin/bash
# postrm script for kotavillage-conf-freeradius

set -e
#set -u

if [ -f /usr/share/debconf/confmodule ]; then
    . /usr/share/debconf/confmodule
fi
if [ -f /usr/share/dbconfig-common/dpkg/postrm.mysql ]; then
    . /usr/share/dbconfig-common/dpkg/postrm.mysql
    dbc_go kotavillage-conf-freeradius $@
fi


if [ "$1" = "purge" ]; then
    rm -f /etc/freeradius/sql.conf.kotavillage
    rm -f /etc/kotavillage/radius.conf
    if which ucf >/dev/null 2>&1; then
        ucf --purge /etc/freeradius/sql.conf.kotavillage
        ucf --purge /etc/kotavillage/radius.conf
        ucfr --purge kotavillage-conf-freeradius /etc/kotavillage/radius.conf
        ucfr --purge kotavillage-conf-freeradius /etc/freeradius/sql.conf.kotavillage
    fi
fi

#DEBHELPER#



if which invoke-rc.d >/dev/null 2>&1; then
       invoke-rc.d freeradius stop || true
else
       /etc/init.d/freeradius stop || true
fi

exit 0
