#!/bin/sh -e

action="$1"
oldversion="$2"

umask 022

# source debconf stuff
. /usr/share/debconf/confmodule
# source dbconfig-common stuff
. /usr/share/dbconfig-common/dpkg/postinst.mysql

mkdir -p /etc/kotavillage/

dbc_first_version=3.0
dbc_generate_include="template:/etc/kotavillage/radius.conf"
dbc_generate_include_perms="660"
dbc_generate_include_owner="freerad:www-data"
dbc_generate_include_args="-o template_infile=/usr/share/kotavillage/templates/radius.conf -U"

dbc_go kotavillage-conf-freeradius $@

## Generate second config file
dbconfig-generate-include -a -f template -O root:freerad -m 660 -o template_infile=/usr/share/kotavillage/templates/sql.conf.kotavillage /etc/dbconfig-common/kotavillage-conf-freeradius.conf /etc/freeradius/sql.conf.kotavillage

if [ "$action" != configure ]
  then
  exit 0
fi

sed -i 's/testing123/hotspotradius/m' /etc/freeradius/clients.conf
#sed -i 's/#.+\$INCLUDE sql.conf/\$INCLUDE sql.conf/m' radiusd.conf
#sed -i 's/#.+\$INCLUDE sql/mysql/counter.conf/\$INCLUDE sql/mysql/counter.conf/m' radiusd.conf


chown root:freerad /etc/freeradius/sql.conf.kotavillage
chmod 640 /etc/freeradius/sql.conf.kotavillage

# On the off chance the radius.conf file is wrong, we need to make sure its right
chown freerad:www-data /etc/kotavillage/radius.conf

# Fix for Debian/Ubuntu bug to do with Perl
preloader=`grep "export LD_PRELOAD" /etc/default/freeradius || true`
    if [ "$preloader" = "" ]
    then
         #libperl=$(find /usr/lib/ -name "libperl.so*"|awk '(NR == 1 || length < length(shortest)) { shortest = $0 } END { print shortest }')
         touch /etc/default/freeradius
         echo 'export LD_PRELOAD=$(find /usr/lib/ -name "libperl.so*"|sort -n |tail -n 1)' >> /etc/default/freeradius         
         #echo "export LD_PRELOAD=$libperl" >> /etc/default/freeradius
    fi

#DEBHELPER#

if which invoke-rc.d >/dev/null 2>&1; then
       invoke-rc.d freeradius restart 3>&- || true
else
       /etc/init.d/freeradius restart 3>&- || true
fi



exit 0

